import type { NewsSource, PublicNewsSource } from "./types";

export const defaultNewsSources: readonly NewsSource[] = [
  {
    id: "antara-general",
    name: "ANTARA News",
    description: "Berita terbaru dari ANTARA News",
    url: "https://www.antaranews.com",
    rssUrl: "https://www.antaranews.com/rss/terkini.xml",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "antara-business",
    name: "ANTARA Ekonomi",
    description: "Berita ekonomi dari ANTARA News",
    url: "https://www.antaranews.com/ekonomi",
    rssUrl: "https://www.antaranews.com/rss/ekonomi.xml",
    category: "business",
    language: "id",
    country: "id",
  },
  {
    id: "antara-sports",
    name: "ANTARA Olahraga",
    description: "Berita olahraga dari ANTARA News",
    url: "https://www.antaranews.com/olahraga",
    rssUrl: "https://www.antaranews.com/rss/olahraga.xml",
    category: "sports",
    language: "id",
    country: "id",
  },
  {
    id: "antara-technology",
    name: "ANTARA Tekno",
    description: "Berita teknologi dari ANTARA News",
    url: "https://www.antaranews.com/tekno",
    rssUrl: "https://www.antaranews.com/rss/tekno.xml",
    category: "technology",
    language: "id",
    country: "id",
  },
  {
    id: "antara-entertainment",
    name: "ANTARA Hiburan",
    description: "Berita hiburan dari ANTARA News",
    url: "https://www.antaranews.com/hiburan",
    rssUrl: "https://www.antaranews.com/rss/hiburan.xml",
    category: "entertainment",
    language: "id",
    country: "id",
  },
  {
    id: "cnn-general",
    name: "CNN Indonesia Nasional",
    description: "Berita nasional dari CNN Indonesia",
    url: "https://www.cnnindonesia.com/nasional",
    rssUrl: "https://www.cnnindonesia.com/nasional/rss",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "cnn-business",
    name: "CNN Indonesia Ekonomi",
    description: "Berita ekonomi dari CNN Indonesia",
    url: "https://www.cnnindonesia.com/ekonomi",
    rssUrl: "https://www.cnnindonesia.com/ekonomi/rss",
    category: "business",
    language: "id",
    country: "id",
  },
  {
    id: "cnn-sports",
    name: "CNN Indonesia Olahraga",
    description: "Berita olahraga dari CNN Indonesia",
    url: "https://www.cnnindonesia.com/olahraga",
    rssUrl: "https://www.cnnindonesia.com/olahraga/rss",
    category: "sports",
    language: "id",
    country: "id",
  },
  {
    id: "cnn-technology",
    name: "CNN Indonesia Teknologi",
    description: "Berita teknologi dari CNN Indonesia",
    url: "https://www.cnnindonesia.com/teknologi",
    rssUrl: "https://www.cnnindonesia.com/teknologi/rss",
    category: "technology",
    language: "id",
    country: "id",
  },
  {
    id: "cnn-entertainment",
    name: "CNN Indonesia Gaya Hidup",
    description: "Berita gaya hidup dari CNN Indonesia",
    url: "https://www.cnnindonesia.com/gaya-hidup",
    rssUrl: "https://www.cnnindonesia.com/gaya-hidup/rss",
    category: "entertainment",
    language: "id",
    country: "id",
  },
  {
    id: "cnbc-general",
    name: "CNBC Indonesia News",
    description: "Berita umum dari CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/news",
    rssUrl: "https://www.cnbcindonesia.com/news/rss",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "cnbc-business",
    name: "CNBC Indonesia Market",
    description: "Berita market dan bisnis dari CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/market",
    rssUrl: "https://www.cnbcindonesia.com/market/rss",
    category: "business",
    language: "id",
    country: "id",
  },
  {
    id: "cnbc-technology",
    name: "CNBC Indonesia Tech",
    description: "Berita teknologi dari CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/tech",
    rssUrl: "https://www.cnbcindonesia.com/tech/rss",
    category: "technology",
    language: "id",
    country: "id",
  },
  {
    id: "cnbc-entertainment",
    name: "CNBC Indonesia Lifestyle",
    description: "Berita lifestyle dari CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/lifestyle",
    rssUrl: "https://www.cnbcindonesia.com/lifestyle/rss",
    category: "entertainment",
    language: "id",
    country: "id",
  },
  {
    id: "tempo-general",
    name: "Tempo Nasional",
    description: "Berita nasional dari Tempo",
    url: "https://nasional.tempo.co",
    rssUrl: "https://rss.tempo.co/nasional",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "tempo-business",
    name: "Tempo Bisnis",
    description: "Berita bisnis dari Tempo",
    url: "https://bisnis.tempo.co",
    rssUrl: "https://rss.tempo.co/bisnis",
    category: "business",
    language: "id",
    country: "id",
  },
  {
    id: "tempo-sports",
    name: "Tempo Bola",
    description: "Berita olahraga dari Tempo",
    url: "https://bola.tempo.co",
    rssUrl: "https://rss.tempo.co/bola",
    category: "sports",
    language: "id",
    country: "id",
  },
  {
    id: "tempo-technology",
    name: "Tempo Tekno",
    description: "Berita teknologi dari Tempo",
    url: "https://tekno.tempo.co",
    rssUrl: "https://rss.tempo.co/tekno",
    category: "technology",
    language: "id",
    country: "id",
  },
  {
    id: "tempo-entertainment",
    name: "Tempo Seleb",
    description: "Berita hiburan dari Tempo",
    url: "https://seleb.tempo.co",
    rssUrl: "https://rss.tempo.co/seleb",
    category: "entertainment",
    language: "id",
    country: "id",
  },
  {
    id: "republika-general",
    name: "Republika",
    description: "Berita terbaru dari Republika",
    url: "https://www.republika.co.id",
    rssUrl: "https://www.republika.co.id/rss",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "cna-general",
    name: "CNA Indonesia",
    description: "Berita terbaru dari CNA Indonesia",
    url: "https://www.cna.id",
    rssUrl: "https://www.cna.id/api/v1/rss-outbound-feed?_format=xml",
    category: "general",
    language: "id",
    country: "id",
  },
  {
    id: "cna-business",
    name: "CNA Indonesia Bisnis",
    description: "Berita bisnis dari CNA Indonesia",
    url: "https://www.cna.id",
    rssUrl:
      "https://www.cna.id/api/v1/rss-outbound-feed?_format=xml&category=3321",
    category: "business",
    language: "id",
    country: "id",
  },
  {
    id: "cna-sports",
    name: "CNA Indonesia Olahraga",
    description: "Berita olahraga dari CNA Indonesia",
    url: "https://www.cna.id",
    rssUrl:
      "https://www.cna.id/api/v1/rss-outbound-feed?_format=xml&category=3246",
    category: "sports",
    language: "id",
    country: "id",
  },
];

export function toPublicSource(source: NewsSource): PublicNewsSource {
  return {
    id: source.id,
    name: source.name,
    description: source.description ?? `${source.name} Indonesia RSS source`,
    url: source.url,
    category: source.category,
    language: source.language,
    country: source.country,
  };
}
